# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'dotenv'

Dotenv.load

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "distribute beta to testers through firebase app distribution"
  lane :distribute do
      #build_android_app(gradle(
      #    task:"assembledebug",
      #    project_dir: 'android/',
      #))
      sh "fvm flutter build apk"
      # build_android_app is a built-in fastlane action.
      release = firebase_app_distribution(
          app: ENV['ANDROID_APP_ID'],
          testers: "stan.racz7@gmail.com",
          release_notes: "Lots of amazing new features to test out!",
          android_artifact_type:"APK",
          android_artifact_path: "../build/app/outputs/apk/release/app-release.apk"
      )
    end

  #desc "Submit a new Beta Build to Crashlytics Beta"
  #lane :beta do
  #  gradle(task: "clean assembleRelease")
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  #end

  #desc "Deploy a new version to the Google Play"
  #lane :deploy do
  #  gradle(task: "clean assembleRelease")
  #  upload_to_play_store
  #end
end
