# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'dotenv'

Dotenv.load

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "distribute beta to testers through firebase app distribution"
  lane :distribute do
    release = firebase_app_distribution(
        app: ENV['ANDROID_APP_ID'],
        groups: "android-test",
        release_notes_file: "../release_scripts/android_release_notes.txt",
        android_artifact_type:"APK",
        android_artifact_path: "../build/app/outputs/apk/release/app-release.apk"
    )
  end

  desc "personal lane to deliver app to me only through firebase app distribution"
  lane :distributetest do
    release = firebase_app_distribution(
        app: ENV['ANDROID_APP_ID'],
        testers:"stan.racz7@gail.com",
        release_notes_file: "../release_scripts/android_release_notes.txt",
        android_artifact_type:"APK",
        android_artifact_path: "../build/app/outputs/apk/release/app-release.apk"
    )
  end

  lane :build do
    sh "fvm flutter build apk"
  end
end
